### ISSUE TITLE
Add dev tools

### ISSUE THREAD

**Issue by aaronalphonso** [aaronalphonso/housie#41]
Add some additional dev tooling for linting and formatting the code along with suitable configuration:
- bandit
- black
- isort
- pylint

**Comment by Qoyyuum** [comment]
Hi @aaronalphonso. I assume you just want default settings for each of those? Would you like them to be set up with [pre-commit](https://pre-commit.com)?

**Comment by aaronalphonso** [comment]
Hi @Qoyyuum, the default settings (as long as they are reasonable) should be good enough. 

I'd like them to be set up to run as part of Github Actions (rather than pre-commit) as part of the existing `lint` job in relevant [workflows](https://github.com/aaronalphonso/housie/tree/main/.github/workflows).  

The goal is to eventually have a Makefile with targets for `make format` and `make lint` and `make test` (#42 ), that would then run each of the tools. This could then be used both locally and on Github actions to validate PRs and pushes.
