### ISSUE TITLE
Add makefile for easy linting, testing and formatting of code

### ISSUE THREAD

**Issue by aaronalphonso** [aaronalphonso/housie#42]
Add a makefile with targets to conveniently lint, format and test the code.

**Comment by nkilm** [comment]
#### I would like to work on this issue, please assign this to me @aaronalphonso

**Comment by aaronalphonso** [comment]
Hi @nkilm, thanks for your interest! I'd really like #41 to be completed before the Makefile (so that the newly added tools can be included in the makefile lint target as well). Let me know if you'd like to pick that up instead, or if not, you could pick this up once someone else completes that.

**Comment by nkilm** [comment]
@aaronalphonso Alright, I'll work on #41 too.
