### ISSUE TITLE
NameError: name 'DisplayElement' is not defined

### ISSUE THREAD

**Issue by decibyte** [aaronalphonso/housie#7]
Hi there!

Thanks for doing the important foundational work for this game :)

When running it with the most recent version from PyPI (0.1.1), i get this error:

`NameError: name 'DisplayElement' is not defined`

It works if downgrading to 0.1.0.

**Comment by aaronalphonso** [comment]
Hello,

Thank you for bringing this to my attention. 

I have fixed this in version (0.1.2) which is now available on PyPI. :)

**Comment by decibyte** [comment]
Thanks!
